### ISSUE TITLE
Build project inside docker container

### ISSUE THREAD

**Issue by thebongy** [ashikka/sike-service#10]
The dockerfile currently uses ts-node to run the project, it should instead run npm run build, and run the built js files. This is better because:
- ts-node is not supposed to be used in production , and if it is, it should be used with the --transpile-only flag (https://stackoverflow.com/questions/60581617/is-it-a-bad-practise-to-use-ts-node-in-production) 
- having the dockerfile run npm run build is a good idea as it allows you to type check the project when the container is built, which can catch errors related to type issues earlier, instead of during runtime

**Comment by ashikka** [comment]
@thebongy Thank you for pointing this out. Would you like to work on this?

**Comment by thebongy** [comment]
Sex stuff

**Comment by thebongy** [comment]
Sex stuff

**Comment by thebongy** [comment]
Yup sure, i'll take this up
