### ISSUE TITLE
Seperate deps and dev deps correctly

### ISSUE THREAD

**Issue by thebongy** [ashikka/sike-service#9]
![Screenshot_2021-08-07-19-50-46-503_com android chrome](https://user-images.githubusercontent.com/7080652/128603318-f5780a87-f54e-403f-84ca-f5dc107cc702.jpg)

- All @types packages can be moved to dev deps
- Nodemon and ts-node can also be moved to dev deps, as they are only requires during development/testing

**Comment by ashikka** [comment]
@thebongy Nice catch! Would you like to work on this?

**Comment by thebongy** [comment]
Yes, i'll make a PR
